### ISSUE TITLE
Inria数据集

### ISSUE THREAD

**Issue by wakakkakak** [Henryjiepanli/Uncertainty-aware-Network#6]
您好，感谢您做出的杰出贡献！请问您可以分享一下Inria建筑物数据集的网盘资源吗？我在官网上下载的数据集，但它显示文件已损坏，无法使用，期待收到您的回复。

**Comment by Henryjiepanli** [comment]
您好，Inria数据集是把五个子集合在一起，训练和测试大家都是固定的，具体可以参考我的论文在数据集部分的说明


-----原始邮件-----
发件人:wakakkakak ***@***.***>
发送时间:2024-05-31 21:54:41 (星期五)
收件人: Henryjiepanli/Uncertainty-aware-Network ***@***.***>
抄送: HenryLi ***@***.***>, Comment ***@***.***>
主题: Re: [Henryjiepanli/Uncertainty-aware-Network] Inria数据集 (Issue #6)






您好，我并没有在网盘中保存数据集，我看了一下应该是可以下载的。下载链接：https://project.inria.fr/aerialimagelabeling/download/，建议查看一下解压方式

好的谢谢，我看数据集中有001，002，003，004，005五个子集，是任选其一作为输入数据集吗？

**Comment by wakakkakak** [comment]
> 您好，Inria数据集是把五个子集合在一起，训练和测试大家都是固定的，具体可以参考我的论文在数据集部分的说明
> […](#)
> -----原始邮件----- 发件人:wakakkakak ***@***.***> 发送时间:2024-05-31 21:54:41 (星期五) 收件人: Henryjiepanli/Uncertainty-aware-Network ***@***.***> 抄送: HenryLi ***@***.***>, Comment ***@***.***> 主题: Re: [Henryjiepanli/Uncertainty-aware-Network] Inria数据集 (Issue #6) 您好，我并没有在网盘中保存数据集，我看了一下应该是可以下载的。下载链接：[https://project.inria.fr/aerialimagelabeling/download/，建议查看一下解压方式](https://project.inria.fr/aerialimagelabeling/download/%EF%BC%8C%E5%BB%BA%E8%AE%AE%E6%9F%A5%E7%9C%8B%E4%B8%80%E4%B8%8B%E8%A7%A3%E5%8E%8B%E6%96%B9%E5%BC%8F) 好的谢谢，我看数据集中有001，002，003，004，005五个子集，是任选其一作为输入数据集吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

您好，非常感谢您的回复！我在处理Massa马萨州数据集时，发现数据集中的图片出现大量空白像素，请问您也是这样的吗？按照您文章中的描述，原始为137，数据增强到411，应该是未剔除大片空白像素的图像？
如图下所示：
![1](https://github.com/Henryjiepanli/Uncertainty-aware-Network/assets/117575513/9e8dd8f4-0a0f-4949-9415-508cb6437b5f)
![2](https://github.com/Henryjiepanli/Uncertainty-aware-Network/assets/117575513/a4033885-8704-49f4-ac3c-d8a9b8b53d66)

**Comment by Henryjiepanli** [comment]
> > 您好，Inria数据集是把五个子集合在一起，训练和测试大家都是固定的，具体可以参考我的论文在数据集部分的说明
> > […](#)
> > -----原始邮件----- 发件人:wakakkakak _**@**_._**> 发送时间:2024-05-31 21:54:41 (星期五) 收件人: Henryjiepanli/Uncertainty-aware-Network _**@**_.**_> 抄送: HenryLi _**@**_._**>, Comment _**@**_.**_> 主题: Re: [Henryjiepanli/Uncertainty-aware-Network] Inria数据集 (Issue #6) 您好，我并没有在网盘中保存数据集，我看了一下应该是可以下载的。下载链接：[https://project.inria.fr/aerialimagelabeling/download/，建议查看一下解压方式](https://project.inria.fr/aerialimagelabeling/download/%EF%BC%8C%E5%BB%BA%E8%AE%AE%E6%9F%A5%E7%9C%8B%E4%B8%80%E4%B8%8B%E8%A7%A3%E5%8E%8B%E6%96%B9%E5%BC%8F) 好的谢谢，我看数据集中有001，002，003，004，005五个子集，是任选其一作为输入数据集吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 您好，非常感谢您的回复！我在处理Massa马萨州数据集时，发现数据集中的图片出现大量空白像素，请问您也是这样的吗？按照您文章中的描述，原始为137，数据增强到411，应该是未剔除大片空白像素的图像？ 如图下所示： ![1](https://private-user-images.githubusercontent.com/117575513/335792474-9e8dd8f4-0a0f-4949-9415-508cb6437b5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTQ5MjYsIm5iZiI6MTcxNzI5NDYyNiwicGF0aCI6Ii8xMTc1NzU1MTMvMzM1NzkyNDc0LTllOGRkOGY0LTBhMGYtNDk0OS05NDE1LTUwOGNiNjQzN2I1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwMjE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDE0OGFjOWZlMGZkMmMxYWVhMWYxZDBjOTRiZDY4YmZiYzdlMTVhZTM1YTVmODYzY2RkOGFmMzM4M2RiYzI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gt5dwsnaNxZ26lntSE6G9p_L3zJC_c3Asaz6dMN4CzI) ![2](https://private-user-images.githubusercontent.com/117575513/335792479-a4033885-8704-49f4-ac3c-d8a9b8b53d66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTQ5MjYsIm5iZiI6MTcxNzI5NDYyNiwicGF0aCI6Ii8xMTc1NzU1MTMvMzM1NzkyNDc5LWE0MDMzODg1LTg3MDQtNDlmNC1hYzNjLWQ4YTliOGI1M2Q2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwMjE3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDA3YWQwZGIwYzI4M2I3MmViNWI1ZWM1NDc1ZTU4MDBmNDdiNjhmN2ZiYzkwNGYxYTM3NjNkOTA0MzM4ODM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.auG6CAPoLaVglrefLGr3xftZb8wIrKRAG_wK1cRXfPE)

没有吧，这个马赛诸州的建筑物数据集的下载可以去找官网链接
